name: Deploy Website
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        
      - name: Node JS Yükleme
        uses: actions/setup-node@v1
    
      - name: Bağımlılık Yükleme
        run: npm ci
        
      - name: Build Etme
        run: npm run build
        
      - name: Statik Sayfa Oluşturma
        run: npm run generate
        
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: docs
          target_branch: main
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
